### ISSUE TITLE
Copy current line in sidebar bug

### ISSUE THREAD

**Issue by NomarCub** [JeppeKlitgaard/ObsidianTweaks#14]
Executing the copy current line commands in a sidebar document now does them in the main edited document instead.

**Comment by NomarCub** [comment]
All hotkeys seem to be affected, I found the issue tracked [here](https://forum.obsidian.md/t/hotkeys-commands-should-apply-to-sidebar-notes-when-they-are-focused/2740). There's some talk in the thread about it being fixable via plugins.

**Comment by JeppeKlitgaard** [comment]
Unfortunately this arises from a bug/shortcoming in Obsidian itself. While some hacky solution could potentially be made, it would only apply to `ObsidianTweaks` commands and would be impossible to make stable.

I would suggest poking the devs or simply wait until a fix is released in Obsidian.

I realise this is not exactly what you wanted to hear – I hope `ObsidianTweaks` is useful nonetheless, albeit not in the sidebar document.
