### ISSUE TITLE
In 0.16.x, `Set as heading 1` was added to core

### ISSUE THREAD

**Issue by huyz** [JeppeKlitgaard/ObsidianTweaks#17]
It looks like these related shortcuts can now be removed from this plugin.

**Comment by JeppeKlitgaard** [comment]
Unfortunately these are not yet equivalent. The core functionality does not support toggling, which `ObsidianTweaks` does. Heading toggling is something I use myself, so I won't remove that feature unless it is fully superseded by the core functionality.

Thanks for the heads up though!

**Comment by huyz** [comment]
Note that there is also a "Remove heading" hotkey available.
