### ISSUE TITLE
Installation instructions don't seem to work

### ISSUE THREAD

**Issue by elisspace** [JeppeKlitgaard/ObsidianTweaks#2]
Thanks for making this!

I see the manifest.json file, but not the main.js. Should I rename the .ts files to .js and then dump them into the same folder with the manifest file?

**Comment by elisspace** [comment]
Wow, okay, years of using Github and today I finally realized where to find
"releases". Thanks for your patience with my dumb self, and double thanks
for the app. One more piece of constructive feedback to consider: I know
you state that every is off by default, but that comes after you list all
the keybindings. I think it's pretty natural to try out the keybindings
you've listed and get confused when they don't work. Maybe you could
mention something like "these are suggested keybindings which you'll need
to add yourself" and clear it all up. I'm happy to make a pull request that
changes that if you like!

Cheers,
--Eli

**Comment by JeppeKlitgaard** [comment]
I would be happy to take a PR

**Comment by elisspace** [comment]
Cool, I've tried to make it exceedingly clear and more idiot-proof! PR
sent. Thanks again for your help on this! I'm so happy to have this
functionality. Really hope it gets merged into the main code at some point.


--Eli
