### ISSUE TITLE
Error with Better toggle code

### ISSUE THREAD

**Issue by andrezgz** [JeppeKlitgaard/ObsidianTweaks#5]
Hi, it's me again. Don't know if it something new, but I don't remember this behavior before Obsidian 0.13.14

Case A:

1. Suppose I have the following text ->This is a $variable
2. If I set the cursor after letter 'r' -> This is a $var|iable
3. and execute "Obsidian Tweak: Better toggle code", only 'variable' gets added to inline code -> This is a $`variable`

Case B:

1. Suppose I have the following text ->This is a $variable
2. If I select the whole variable name including the dollar sign -> This is a |$variable|
3. and execute "Obsidian Tweak: Better toggle code", I get an error in JS console: `Uncaught TypeError: Cannot read property 'from' of null at BetterFormatting.toggleWrapper`

When debug mode is active, the following is added to the log: `Command failed to execute:  obsidian-tweaks:better-formatting-code`

For case B, if I use the Obsidian "Toggle code" command in step 3, I get what I expect -> This is a `$variable`

Would you be able to make some change to fix it?

**Comment by JeppeKlitgaard** [comment]
Hm. I had assumed that the Obsidian function signature would be the same as that of CM, but this might not be the case.

I'll have a look and see if I can reproduce this. Thank you for the detailed bug report!

**Comment by JeppeKlitgaard** [comment]
Hey @andrezgz,

Version 0.2.4 should address both of these issues. Additionally the 'expansion' logic has been improved to better work around leading and trailing symbols like `@#$` and `:?!`

**Comment by andrezgz** [comment]
Thanks @JeppeKlitgaard, I've updated to 0.2.4 and it's very effective indeed!
